### ISSUE TITLE
[BUG] mppcava shared library issue on Linux Mint

### ISSUE THREAD

**Issue by JOJ0** [doctorfree/MusicPlayerPlus#29]
Hi again, on Linux Mint it seems mppcava faces a similar issue as mpcplus did recently. I open the issue here since your fork of cava repo does not have the issues feature enabled - I think that's a default setting on forks on github. It can still be enabled in the repo's setting if desired btw.

```
$ mppcava
mppcava: error while loading shared libraries: libportaudio.so.2: cannot open shared object file: No such file or directory
```

```
$ apt show mppcava
Package: mppcava
Version: 1.0.1-1
Status: install ok installed
Priority: optional
Section: sound
Maintainer: Ronald Record <ronaldrecord@gmail.com>
Installed-Size: 5.120 kB
Depends: libncursesw6 (>= 6), libfftw3-dev, libiniparser-dev, libsdl2-dev, libasound2, libpulse-dev
Homepage: https://github.com/doctorfree/mppcava
Build-Depends: debhelper (>= 11)
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Bar audio spectrum visualizer

$ lsb_release -a
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 21.1
Release:        21.1
Codename:       vera
```

**Comment by doctorfree** [comment]
Enabled issues in `mppcava` repo and copied this issue to https://github.com/doctorfree/mppcava/issues/1#issue-1552197500

This looks like a missing dependency on `libportaudio` and should be easier to fix than the shared libs problem with `mpcplus`.

Closing this issue, continue to follow at the above issue link in mppcava
